name: Saucedemo.com-Tests

on: [push, pull_request]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
            
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'   # my Python version

      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright pytest
          playwright install

      - name: Run tests
        run: |
          python -m pytest POM/Tests

      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: TestReports
          path: |
            reports/results.xml
            Saucedemo.com-automation/screenshots/  

